"""
trim_idle_lerobot.py — Trim idle frames from a LeRobot v2.1 dataset using
the official LeRobot 0.3.x API, with batch-decode + GPU-encode acceleration.
 
Speedups vs naive lerobot-only path:
  - Batch decode each episode video once (avoids per-frame seek, ~10x faster).
  - PTS-ordered frame list (correctness against B-frame reorder).
  - GPU h264_nvenc when available, falls back to CPU h264, then libsvtav1.
  - Bulk pandas column access instead of df.iloc[i][k] (5-10x faster).
  - Pre-stack vector columns once per episode.
 
Correctness preserved:
  - Per-episode normalization stats recomputed by lerobot's save_episode().
  - meta/info.json, episodes.jsonl, tasks.jsonl auto-managed.
  - frame_index / timestamp / index regenerated by lerobot.
  - chunk path computed from chunks_size (works for >=1000 episodes).
  - Frame-vs-parquet length asserted before any writes.
 
Tested target:
  - lerobot == 0.3.3
  - dataset codebase_version == "v2.1"
 
Gripper convention assumed:
  action 0 -> 1  =  OPEN
  action 1 -> 0  =  CLOSE

Multi-arm / multi-camera:
  - Video keys are auto-detected from features (dtype == "video"), so any
    number of cameras (e.g. 3) is handled with no code changes.
  - Idle detection treats EVERY non-gripper action dim as a motion dim and
    every gripper (configurable list of indices) independently. A frame is
    idle only if the arm is not being commanded to move AND all grippers are
    static. Gripper events / close-protection take the union across grippers.
  - The arm-motion signal depends on what `action` means (--motion-idle-mode):
        target : action is an ABSOLUTE target position (controller setpoint);
                 idle when the target is unchanged frame-to-frame.   [default]
        delta  : action dims are deltas/velocities; idle when ~0.
  - Default dual-arm UR3 action layout (16-dim):
        [0..6]  left  arm eef
        [7..13] right arm eef
        [14]    left  gripper
        [15]    right gripper
    observation.state uses the SAME 16-dim layout, so the gripper indices
    match: --gripper-act-idx 14,15 and --gripper-obs-idx 14,15 (both default).
"""
 
import argparse
import contextlib
import os
import shutil
import sys
from pathlib import Path
 
import av
import numpy as np
import pandas as pd
 
from lerobot.datasets.lerobot_dataset import LeRobotDataset
import lerobot.datasets.video_utils as _vid_utils
import lerobot.datasets.lerobot_dataset as _lr_mod
 
 
NUMERIC_DTYPES = {"float32", "float64", "int32", "int64", "bool",
                  "uint8", "uint16", "uint32", "uint64", "int8", "int16"}


def _parse_idx_list(s):
    """Parse a comma-separated index list, e.g. '14,15' -> [14, 15]."""
    if isinstance(s, (list, tuple)):
        return [int(x) for x in s]
    return [int(x) for x in str(s).split(",") if str(x).strip() != ""]
 
 
# ============================================================
# Encoder auto-detection (silent, robust)
# ============================================================
 
def _probe_encoder(codec: str) -> bool:
    """Try to encode one black frame; return True if the encoder works."""
    try:
        with contextlib.redirect_stderr(open(os.devnull, "w")):
            c = av.open(os.devnull, "w", format="null")
            s = c.add_stream(codec, rate=30)
            s.width, s.height, s.pix_fmt = 64, 64, "yuv420p"
            f = av.VideoFrame(64, 64, "yuv420p")
            for plane in f.planes:
                plane.update(bytes(plane.buffer_size))  # zero-fill (black)
            list(s.encode(f))
            list(s.encode(None))  # flush
            c.close()
        return True
    except Exception:
        return False
 
 
def _detect_best_encoder() -> str:
    """nvenc (GPU) > h264 (CPU) > libsvtav1 (CPU AV1, lerobot default)."""
    for codec in ("h264_nvenc", "h264", "libsvtav1"):
        if _probe_encoder(codec):
            return codec
    raise RuntimeError("No working video encoder found (tried nvenc/h264/svtav1).")
 
 
_FAST_CODEC = _detect_best_encoder()
print(f"[encoder] using {_FAST_CODEC}", file=sys.stderr)
 
 
def _fast_encode_video_frames(imgs_dir, video_path, fps, vcodec=None,
                              pix_fmt="yuv420p", g=2, **_):
    """Replacement for lerobot's encode_video_frames.
    Honors GOP=2 (lerobot's default for accurate seeking)."""
    import glob
    from PIL import Image
 
    if vcodec is None:
        vcodec = _FAST_CODEC
 
    video_path = Path(video_path)
    imgs_dir = Path(imgs_dir)
    video_path.parent.mkdir(parents=True, exist_ok=True)
 
    template = "frame_" + ("[0-9]" * 6) + ".png"
    input_list = sorted(
        glob.glob(str(imgs_dir / template)),
        key=lambda x: int(x.split("_")[-1].split(".")[0])
    )
    if not input_list:
        raise FileNotFoundError(f"No images found in {imgs_dir}.")
 
    width, height = Image.open(input_list[0]).size
    video_options = {"g": str(g)} if g is not None else {}
    if "nvenc" in vcodec:
        video_options["bf"] = "0"  # nvenc B-frame support is iffy
 
    with av.open(str(video_path), "w") as output:
        stream = output.add_stream(vcodec, fps, options=video_options)
        stream.pix_fmt = pix_fmt
        stream.width = width
        stream.height = height
        for path in input_list:
            frame = av.VideoFrame.from_image(Image.open(path).convert("RGB"))
            for pkt in stream.encode(frame):
                output.mux(pkt)
        for pkt in stream.encode():
            output.mux(pkt)
 
    if not video_path.exists():
        raise OSError(f"Video encoding failed: {video_path}")
 
 
# Patch BOTH module entries (lerobot imports it into its main module too)
_vid_utils.encode_video_frames = _fast_encode_video_frames
_lr_mod.encode_video_frames = _fast_encode_video_frames
 
 
# ============================================================
# Path helpers (chunk-aware)
# ============================================================
 
def episode_paths(src_root: Path, ep_idx: int, chunks_size: int, video_keys):
    chunk = f"chunk-{ep_idx // chunks_size:03d}"
    pq = src_root / "data" / chunk / f"episode_{ep_idx:06d}.parquet"
    videos = {vk: src_root / "videos" / chunk / vk / f"episode_{ep_idx:06d}.mp4"
              for vk in video_keys}
    return pq, videos
 
 
# ============================================================
# Idle detection
# ============================================================
 
def motion_signal(actions, motion_idxs, motion_mode):
    """Per-frame 'how much the arm is being commanded to move', for the
    non-gripper action dims.

    motion_mode:
      "target" -> action is an ABSOLUTE target position (controller setpoint).
                  A frame is moving iff the target changes vs the previous
                  frame, so the signal is |action[t] - action[t-1]|.
      "delta"  -> action dims are already deltas/velocities, so the signal is
                  |action[t]| directly (original single-arm behavior).
    """
    motion = actions[:, motion_idxs]
    if motion_mode == "delta":
        return np.abs(motion)
    # "target": temporal difference; frame 0 inherits frame 1's value.
    d = np.abs(np.diff(motion, axis=0))
    if len(d) == 0:                      # T <= 1
        return np.zeros_like(motion)
    return np.vstack([d[:1], d])


def find_idle_mask(actions, obs_states, threshold,
                   gripper_act_idxs, gripper_obs_idxs, motion_mode="target"):
    """Idle = arm not being commanded to move AND every gripper static.

    - Arm: motion_signal(...) < threshold on every non-gripper dim. For
      absolute target positions (motion_mode="target") this means the
      commanded target is not changing frame-to-frame.
    - Gripper: |gripper_action - gripper_state| < threshold per gripper
      (target reached and held). Correct for absolute gripper targets too.

    Works for any number of arms/grippers.
    """
    gripper_set = set(gripper_act_idxs)
    motion_idxs = [i for i in range(actions.shape[1]) if i not in gripper_set]
    sig = motion_signal(actions, motion_idxs, motion_mode)
    vel_idle = np.all(sig < threshold, axis=1)

    gripper_idle = np.ones(actions.shape[0], dtype=bool)
    for a_idx, o_idx in zip(gripper_act_idxs, gripper_obs_idxs):
        gripper_idle &= np.abs(actions[:, a_idx] - obs_states[:, o_idx]) < threshold
    return vel_idle & gripper_idle
 
 
def find_contiguous_segments(mask):
    segs, in_seg, start = [], False, 0
    for i, v in enumerate(mask):
        if v and not in_seg:
            start, in_seg = i, True
        elif not v and in_seg:
            segs.append((start, i))
            in_seg = False
    if in_seg:
        segs.append((start, len(mask)))
    return segs
 
 
def classify_segments(idle_segments, n_frames):
    out = []
    for s, e in idle_segments:
        if s == 0:
            kind = "leading"
        elif e == n_frames:
            kind = "trailing"
        else:
            kind = "middle"
        out.append((kind, s, e))
    return out
 
 
def gripper_transitions(actions, gripper_act_idxs):
    """Collect (frame, event) across all grippers, sorted by frame.
    Convention: 1 = open, 0 = close. Use post-transition value."""
    events = []
    for a_idx in gripper_act_idxs:
        g = actions[:, a_idx]
        diffs = np.abs(np.diff(g))
        for t in np.where(diffs > 0.4)[0]:
            post = g[t + 1] if (t + 1) < len(g) else g[t]
            events.append((int(t), "open" if post > 0.5 else "close"))
    events.sort(key=lambda x: x[0])
    return events


def map_gripper_events_to_idles(actions, gripper_act_idxs, idle_segments,
                                n_frames, max_gap_frames=30):
    """Label each middle idle segment with the gripper event (open/close) of
    ANY gripper that transitioned shortly before it."""
    events = gripper_transitions(actions, gripper_act_idxs)
 
    classified = classify_segments(idle_segments, n_frames)
    mid_segs = [(i, s, e) for i, (kind, s, e) in enumerate(classified)
                if kind == "middle"]
 
    labels = {}
    for t, event in events:
        for seg_i, s, e in mid_segs:
            if seg_i in labels:
                continue
            if s > t and (s - t) <= max_gap_frames:
                labels[seg_i] = event
                break
    return labels
 
 
def compute_keep_mask(n_frames, idle_mask, actions, gripper_act_idxs,
                      start_keep, end_keep, mid_keep, min_idle_len,
                      fps, close_protect_sec=2.0, max_gap_frames=30):
    keep = np.ones(n_frames, dtype=bool)
    info = []

    # Close protection: keep all idle within 2s after ANY gripper's close
    # transition (1->0), across all grippers.
    close_protect_frames = int(round(fps * close_protect_sec))
    close_protected = np.zeros(n_frames, dtype=bool)
    for t, event in gripper_transitions(actions, gripper_act_idxs):
        if event == "close":  # action went 1->0, post value ~0
            prot_end = min(n_frames, t + 1 + close_protect_frames)
            close_protected[t + 1: prot_end] = True

    idle_segments = find_contiguous_segments(idle_mask)
    classified = classify_segments(idle_segments, n_frames)
    gripper_labels = map_gripper_events_to_idles(
        actions, gripper_act_idxs, idle_segments, n_frames, max_gap_frames)

    for seg_i, (kind, s, e) in enumerate(classified):
        seg_len = e - s
        if seg_len < min_idle_len:
            continue

        if kind == "middle":
            if np.any(close_protected[s:e]):
                info.append({"kind": "mid-close-protect", "start": s, "end": e,
                             "seg_len": seg_len, "dropped": 0})
                continue
            event = gripper_labels.get(seg_i)
            if event in ("open", "close"):
                info.append({"kind": f"mid-{event}", "start": s, "end": e,
                             "seg_len": seg_len, "dropped": 0})
                continue
            max_keep = mid_keep
        elif kind == "leading":
            max_keep = start_keep
        else:
            max_keep = end_keep

        if seg_len <= max_keep:
            continue
        if kind == "leading":
            ds, de = s, e - max_keep
        elif kind == "trailing":
            ds, de = s + max_keep, e
        elif max_keep == 0:
            ds, de = s, e
        else:
            half = max_keep // 2
            ds, de = s + half, e - (max_keep - half)
        keep[ds:de] = False
        label = "mid-idle" if kind == "middle" else kind
        info.append({"kind": label, "start": s, "end": e,
                     "seg_len": seg_len, "dropped": de - ds})
    return keep, info
 
 
# ============================================================
# Video decode (PTS-ordered, batch)
# ============================================================
 
def find_last_release(actions, gripper_act_idxs):
    """Frame index of the FINAL gripper release (closed->open) across all
    grippers, or None if none is detected.

    A release = the manipulating gripper opening after a grasp (final block
    placed). The idle arm's gripper never actuates, so taking the last release
    over all grippers isolates the last real placement regardless of which arm
    manipulated in this episode."""
    last = None
    for gi in gripper_act_idxs:
        g = np.asarray(actions[:, gi])
        lo, hi = float(g.min()), float(g.max())
        if hi - lo < 0.4:               # this gripper never actuates this episode
            continue
        mid = 0.5 * (lo + hi)
        closed = g < mid
        rel = np.where(closed[:-1] & ~closed[1:])[0] + 1   # closed -> open
        if len(rel):
            last = int(rel[-1]) if last is None else max(last, int(rel[-1]))
    return last


def compute_tail_keep_mask(n_frames, actions, gripper_act_idxs, margin):
    """Keep [0 : last_release + margin]; drop the post-placement retract/wobble.

    The demos keep teleoperating (arm retract, hand-off jitter) for a while
    after the final block is released — that trailing motion is task-irrelevant
    and is actively harmful to learn (it is real motion, so the idle trimmer
    never catches it). Truncating right after the final release + a short settle
    margin removes it. Falls back to keeping the whole episode if no release is
    detected."""
    keep = np.ones(n_frames, dtype=bool)
    last = find_last_release(actions, gripper_act_idxs)
    if last is None:
        return keep, [{"kind": "no-release", "start": 0, "end": n_frames,
                       "seg_len": n_frames, "dropped": 0}]
    cut = min(last + margin, n_frames)
    info = []
    if cut < n_frames:
        keep[cut:] = False
        info.append({"kind": "tail", "start": cut, "end": n_frames,
                     "seg_len": n_frames - cut, "dropped": n_frames - cut})
    return keep, info


def decode_episode_video(video_path: Path) -> list:
    """Decode all frames as HWC uint8 RGB, sorted by PTS (display order).
 
    PyAV's container.decode() typically returns in display order, but with
    B-frames or multi-threaded decode it MAY return in decode order. We
    sort explicitly by PTS to be safe — this is critical for frame-vs-action
    alignment.
    """
    container = av.open(str(video_path))
    stream = container.streams.video[0]
    # Single-threaded decode for deterministic ordering. The cost is small
    # vs the win of avoiding silent frame-vs-action misalignment.
    stream.thread_type = "NONE"
 
    frames_with_pts = []
    fallback_idx = 0
    for frame in container.decode(stream):
        pts = frame.pts if frame.pts is not None else fallback_idx
        fallback_idx += 1
        frames_with_pts.append((pts, frame.to_ndarray(format="rgb24")))
    container.close()
 
    frames_with_pts.sort(key=lambda x: x[0])
    return [f for _, f in frames_with_pts]
 
 
# ============================================================
# Episode info
# ============================================================
 
def get_episode_bounds(src_ds, ep_idx):
    edi = getattr(src_ds, "episode_data_index", None)
    if edi is not None and "from" in edi and "to" in edi:
        return int(edi["from"][ep_idx].item()), int(edi["to"][ep_idx].item())
    lengths = [src_ds.meta.episodes[i]["length"]
               for i in range(src_ds.meta.total_episodes)]
    starts = np.cumsum([0] + lengths[:-1])
    return int(starts[ep_idx]), int(starts[ep_idx] + lengths[ep_idx])
 
 
def resolve_episode_task(src_ds, ep_idx, src_root, chunks_size):
    chunk = f"chunk-{ep_idx // chunks_size:03d}"
    pq = src_root / "data" / chunk / f"episode_{ep_idx:06d}.parquet"
    ti = int(pd.read_parquet(pq, columns=["task_index"])["task_index"].iloc[0])
    tasks = src_ds.meta.tasks
    return tasks[ti] if isinstance(tasks, dict) else tasks[ti]
 
 
# ============================================================
# Main rebuild
# ============================================================
 
def analyze_and_rebuild(args):
    src_root = Path(args.src).resolve()
    dst_root = Path(args.dst).resolve() if args.dst else None
 
    print(f"[load] {src_root}")
    src_ds = LeRobotDataset(repo_id=args.src_repo_id, root=src_root,
                            video_backend="pyav")
    chunks_size = src_ds.meta.info.get("chunks_size", 1000)
    print(f"  codebase_version={src_ds.meta.info.get('codebase_version')}, "
          f"fps={src_ds.fps}, total_episodes={src_ds.meta.total_episodes}, "
          f"total_frames={src_ds.meta.total_frames}, chunks_size={chunks_size}")
    print(f"  features: {list(src_ds.meta.features.keys())}")
 
    AUTO_KEYS = {"timestamp", "frame_index", "episode_index", "index", "task_index"}
    out_features = {k: v for k, v in src_ds.meta.features.items()
                    if k not in AUTO_KEYS}
    video_keys = [k for k, v in out_features.items() if v["dtype"] == "video"]
    non_video_keys = [k for k in out_features if k not in video_keys]
    print(f"  video features: {video_keys}")
 
    # ---- analyze ----
    plan = []
    total_before = total_after = total_idle = 0
    n_empty = 0
 
    for ep_idx in range(src_ds.meta.total_episodes):
        ep_from, ep_to = get_episode_bounds(src_ds, ep_idx)
        ep_length = ep_to - ep_from
 
        pq_path, _ = episode_paths(src_root, ep_idx, chunks_size, video_keys)
        df = pd.read_parquet(pq_path)
        actions = np.stack(df["action"].values)
        obs_states = np.stack(df["observation.state"].values)
 
        if ep_idx == 0:
            gripper_set = set(args.gripper_act_idxs)
            motion_idxs = [i for i in range(actions.shape[1])
                           if i not in gripper_set]
            print(f"\n[sanity] episode 0 stats:")
            print(f"  action shape:    {actions.shape}")
            print(f"  gripper act idxs: {args.gripper_act_idxs}  "
                  f"obs idxs: {args.gripper_obs_idxs}")
            print(f"  motion (non-gripper) action idxs: {motion_idxs}")
            print(f"  motion-idle-mode: {args.motion_idle_mode}")
            sig = motion_signal(actions, motion_idxs, args.motion_idle_mode)
            print(f"  motion signal median per dim: "
                  f"{np.round(np.median(sig, axis=0), 5)}")
            print(f"  frames with all motion < {args.threshold}: "
                  f"{int(np.all(sig < args.threshold, axis=1).sum())}/{len(actions)}")
            print(f"  action min:      {np.round(actions.min(0), 4)}")
            print(f"  action max:      {np.round(actions.max(0), 4)}")
            print(f"  obs_state shape: {obs_states.shape}")
            for a_idx, o_idx in zip(args.gripper_act_idxs, args.gripper_obs_idxs):
                g = actions[:, a_idx]
                n_trans = int((np.abs(np.diff(g)) > 0.4).sum())
                print(f"  gripper act[{a_idx}] range "
                      f"[{g.min():.4f}, {g.max():.4f}] vs "
                      f"obs[{o_idx}] range "
                      f"[{obs_states[:, o_idx].min():.4f}, "
                      f"{obs_states[:, o_idx].max():.4f}]  "
                      f"transitions={n_trans}")
            print(f"  convention: 0->1 OPEN, 1->0 CLOSE\n")

        if args.mode == "tail":
            margin = int(round(args.tail_margin_s * src_ds.fps))
            keep, info = compute_tail_keep_mask(
                ep_length, actions, args.gripper_act_idxs, margin)
            idle_n = 0
        else:
            idle_mask = find_idle_mask(actions, obs_states, args.threshold,
                                       args.gripper_act_idxs, args.gripper_obs_idxs,
                                       motion_mode=args.motion_idle_mode)
            keep, info = compute_keep_mask(
                ep_length, idle_mask, actions, args.gripper_act_idxs,
                args.start_keep, args.end_keep, args.mid_keep, args.min_idle_len,
                fps=src_ds.fps, max_gap_frames=int(round(src_ds.fps)))
            idle_n = int(idle_mask.sum())
        n_after = int(keep.sum())
 
        plan.append((ep_idx, ep_from, ep_to, keep, info))
        total_before += ep_length
        total_after += n_after
        total_idle += idle_n
        if n_after == 0:
            n_empty += 1
 
        marker = " ***" if n_after != ep_length else ""
        empty_marker = " <EMPTY>" if n_after == 0 else ""
        print(f"  ep{ep_idx:04d}: {ep_length:>5} -> {n_after:>5}  "
              f"(idle {idle_n}/{ep_length} = {idle_n/ep_length*100:.1f}%)"
              f"{marker}{empty_marker}")
        for seg in info:
            print(f"      {seg['kind']:>9}: [{seg['start']}:{seg['end']}] "
                  f"len={seg['seg_len']} dropped={seg['dropped']}")
 
    print(f"\n[summary]")
    print(f"  total: {total_before} -> {total_after}  "
          f"(dropped {total_before-total_after}, "
          f"{(total_before-total_after)/total_before*100:.2f}%)")
    print(f"  idle: {total_idle}/{total_before} "
          f"({total_idle/total_before*100:.2f}%) before; "
          f"~{(total_idle - (total_before-total_after))/max(total_after,1)*100:.2f}% after")
    if n_empty > 0:
        print(f"  WARNING: {n_empty} episode(s) would become empty.")
 
    if args.dry_run:
        print("\n[dry-run] no output written.")
        return
 
    # ---- create destination ----
    if dst_root is None:
        raise ValueError("--dst is required when not in --dry-run mode")
    if dst_root.exists():
        if args.overwrite:
            print(f"[clean] removing existing {dst_root}")
            shutil.rmtree(dst_root)
        else:
            raise FileExistsError(
                f"{dst_root} already exists. Pass --overwrite to replace.")
 
    print(f"\n[create] {dst_root}  repo_id={args.dst_repo_id}")
    dst_ds = LeRobotDataset.create(
        repo_id=args.dst_repo_id,
        fps=src_ds.fps,
        root=dst_root,
        features=out_features,
        use_videos=True,
        image_writer_threads=args.image_writer_threads,
        image_writer_processes=args.image_writer_processes,
    )
 
    # ---- per-episode rebuild (batch decode + bulk pandas access) ----
    n_written_eps = 0
    for ep_idx, ep_from, ep_to, keep, _ in plan:
        keep_local = np.where(keep)[0]
        if len(keep_local) == 0:
            print(f"  ep{ep_idx:04d}: SKIPPED (empty after trim)")
            continue
 
        ep_length = ep_to - ep_from
        pq_path, video_paths = episode_paths(src_root, ep_idx,
                                             chunks_size, video_keys)
        task = resolve_episode_task(src_ds, ep_idx, src_root, chunks_size)
 
        # Read parquet once; pre-stack vector columns for fast indexing
        df = pd.read_parquet(pq_path)
        if len(df) != ep_length:
            raise RuntimeError(
                f"ep{ep_idx}: parquet has {len(df)} rows, expected {ep_length}")
        col_arrays = {}
        for k in non_video_keys:
            col = df[k].values
            if len(col) > 0 and isinstance(col[0], np.ndarray):
                col_arrays[k] = np.stack(col)  # (T, D)
            else:
                col_arrays[k] = np.asarray(col)
 
        # Batch decode each video stream and assert sync
        vid_frames = {}
        for vk in video_keys:
            frames = decode_episode_video(video_paths[vk])
            if len(frames) != ep_length:
                raise RuntimeError(
                    f"ep{ep_idx}: video {vk} has {len(frames)} frames, "
                    f"expected {ep_length} (parquet rows). "
                    f"Refusing to write — would corrupt frame-action alignment.")
            vid_frames[vk] = frames
 
        # Add the kept frames
        for local_i in keep_local:
            local_i = int(local_i)
            frame = {}
            for vk in video_keys:
                frame[vk] = vid_frames[vk][local_i]   # already HWC uint8
            for k in non_video_keys:
                v = col_arrays[k][local_i]
                dtype = out_features[k]["dtype"]
                if dtype in NUMERIC_DTYPES:
                    v = np.asarray(v, dtype=dtype)
                frame[k] = v
            dst_ds.add_frame(frame, task=task)
 
        del vid_frames, col_arrays, df
        dst_ds.save_episode()
        n_written_eps += 1
        print(f"  ep{ep_idx:04d}: saved {len(keep_local)} frames")
 
    print(f"\n[done] wrote {n_written_eps} episodes, "
          f"{dst_ds.meta.total_frames} frames -> {dst_root}")
    print("Sanity: open meta/info.json and confirm total_frames / total_episodes match.")
 
 
def main():
    p = argparse.ArgumentParser()
    p.add_argument("--src", required=True)
    p.add_argument("--dst", default=None)
    p.add_argument("--src-repo-id", default="local/source")
    p.add_argument("--dst-repo-id", default="local/trimmed")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--overwrite", action="store_true")
    p.add_argument("--mode", choices=["idle", "tail"], default="idle",
                   help="'idle' (default): drop static idle segments. "
                        "'tail': truncate each episode after the FINAL gripper "
                        "release + margin, removing the post-placement retract/"
                        "wobble that the idle trimmer cannot catch.")
    p.add_argument("--tail-margin-s", type=float, default=0.5,
                   help="[tail mode] seconds to keep after the final release "
                        "(lets the block settle / gripper clear) before cutting.")
    p.add_argument("--threshold", type=float, default=0.01)
    p.add_argument("--motion-idle-mode", choices=["target", "delta"],
                   default="target",
                   help="'target' (default): action is an absolute target "
                        "position, idle = target unchanged frame-to-frame. "
                        "'delta': action dims are deltas/velocities, idle = "
                        "magnitude near zero (original single-arm behavior).")
    p.add_argument("--gripper-act-idx", default="14,15",
                   help="Comma-separated gripper indices in the action vector "
                        "(dual-arm UR3 default: 14,15 = left,right).")
    p.add_argument("--gripper-obs-idx", default="14,15",
                   help="Comma-separated gripper indices in observation.state, "
                        "matched 1:1 with --gripper-act-idx. Dual-arm UR3 "
                        "default 14,15 (state is same layout as action).")
    p.add_argument("--start-keep", type=int, default=5)
    p.add_argument("--end-keep", type=int, default=10)
    p.add_argument("--mid-keep", type=int, default=0)
    p.add_argument("--min-idle-len", type=int, default=5)
    p.add_argument("--image-writer-threads", type=int, default=4)
    p.add_argument("--image-writer-processes", type=int, default=0)
    args = p.parse_args()
 
    if not args.dry_run and args.dst is None:
        p.error("--dst is required unless --dry-run is set")

    args.gripper_act_idxs = _parse_idx_list(args.gripper_act_idx)
    args.gripper_obs_idxs = _parse_idx_list(args.gripper_obs_idx)
    if len(args.gripper_act_idxs) != len(args.gripper_obs_idxs):
        p.error("--gripper-act-idx and --gripper-obs-idx must have the same "
                f"number of entries (got {args.gripper_act_idxs} vs "
                f"{args.gripper_obs_idxs})")

    analyze_and_rebuild(args)
 
 
if __name__ == "__main__":
    main()